# Leave this
github: [metadata]

# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: dieghernan/chulapa
plugins:
- jekyll-remote-theme

title: ROAM 2025 workshop
description: Autonomous Robots for Outdoor Mobility and Exploration
